sudo: false
language: php
php:
  - 5.4
  - 5.5


env:
  - MAGENTO_VERSION=magento-mirror-1.9.2.3
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2

services:
  - mysql

# Deletes build directoy and adds new tools
install:
  # Clean build directory
  - rm -rf build; mkdir build; cd build

  # install coveralls
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar --version

  # install modman
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - modman --version

  # install n98-magerun
  - wget https://files.magerun.net/n98-magerun.phar
  - chmod +x n98-magerun.phar
  - ./n98-magerun.phar --version

  - export PATH=$PWD:$PATH

before_script:
  # Clean mysql database
  - mysql -e "DROP DATABASE IF EXISTS magento_test; CREATE DATABASE IF NOT EXISTS magento_test;" -uroot

  - cd $TRAVIS_BUILD_DIR/build

  # Install Magento
  - n98-magerun.phar install --magentoVersion ${MAGENTO_VERSION} --installationFolder "magento" --dbHost "127.0.0.1" --dbUser "root" --dbPass "" --dbName "magento_test" --baseUrl "http://testmagento.local" --forceUseDb --useDefaultConfigParams yes --installSampleData no
  - mkdir -p magento/var/log

  # Install our module
  - cd $TRAVIS_BUILD_DIR/build/magento
  - n98-magerun.phar sys:info
  - modman init
  - modman link $TRAVIS_BUILD_DIR

  # Install EcomDev_PHPUnit
  - modman clone git://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd shell
  - php ecomdev-phpunit.php -a magento-config -r --db-name "magento_test" --same-db true --base-url "http://testmagento.local"

  - n98-magerun.phar sys:modules:list | grep -e 'Sheep\|EcomDev_PHPUnit'


script:
  - cd $TRAVIS_BUILD_DIR/build
  - mkdir logs

  - cd $TRAVIS_BUILD_DIR/build/magento
  - cp $TRAVIS_BUILD_DIR/phpunit.xml .
  - phpunit -c phpunit.xml --group Sheep_Debug --coverage-clover ../logs/clover.xml

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls.phar -v
